// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtSkLMC5eWa5WUjzWyu56RWuPeeBlD9gg',
    appId: '1:120810655315:web:50ecffb2951d652bb7c0a6',
    messagingSenderId: '120810655315',
    projectId: 'dmpdb-8f26e',
    authDomain: 'dmpdb-8f26e.firebaseapp.com',
    databaseURL: 'https://dmpdb-8f26e-default-rtdb.firebaseio.com',
    storageBucket: 'dmpdb-8f26e.firebasestorage.app',
    measurementId: 'G-5HC91PXP3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbkSaGxcV0Z2_sAq8-E4bbdMvqUGqDHDo',
    appId: '1:120810655315:android:38c6373028ab6540b7c0a6',
    messagingSenderId: '120810655315',
    projectId: 'dmpdb-8f26e',
    databaseURL: 'https://dmpdb-8f26e-default-rtdb.firebaseio.com',
    storageBucket: 'dmpdb-8f26e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA30DZdDptPkHzlUqAD5VvEQ53d8zvH9Ig',
    appId: '1:120810655315:ios:5db4001395c87298b7c0a6',
    messagingSenderId: '120810655315',
    projectId: 'dmpdb-8f26e',
    databaseURL: 'https://dmpdb-8f26e-default-rtdb.firebaseio.com',
    storageBucket: 'dmpdb-8f26e.firebasestorage.app',
    iosClientId: '120810655315-lqk3caibr2a6qcjk5s4mc0jrq0g2s5ug.apps.googleusercontent.com',
    iosBundleId: 'com.example.dmp',
  );
}
